using System;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using System.Web;
using GuildArena.Domain.Entities;
using GuildArena.Infrastructure.Options;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace GuildArena.Infrastructure.Services.Email;

/// <summary>
/// A custom implementation of IEmailSender using the modern Brevo v3 REST API.
/// Responsible for dispatching Identity emails and rewriting API links to SPA links.
/// </summary>
public class BrevoEmailSender : IEmailSender<ApplicationUser>
{
    private readonly IHttpClientFactory _httpClientFactory;
    private readonly BrevoOptions _options;
    private readonly ILogger<BrevoEmailSender> _logger;

    public BrevoEmailSender(
        IHttpClientFactory httpClientFactory,
        IOptions<BrevoOptions> options,
        ILogger<BrevoEmailSender> logger)
    {
        _httpClientFactory = httpClientFactory ?? throw new ArgumentNullException(nameof(httpClientFactory));
        _options = options?.Value ?? throw new ArgumentNullException(nameof(options));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <summary>
    /// Extracts the query parameters from the backend-generated confirmation link,
    /// rewrites the URL to point to the Blazor SPA, and dispatches the email.
    /// </summary>
    public async Task SendConfirmationLinkAsync(ApplicationUser user, string email, string confirmationLink)
    {
        ArgumentNullException.ThrowIfNull(user);
        ArgumentException.ThrowIfNullOrWhiteSpace(email);
        ArgumentException.ThrowIfNullOrWhiteSpace(confirmationLink);

        var uri = new Uri(confirmationLink);
        var query = HttpUtility.ParseQueryString(uri.Query);
        var userId = query["userId"];
        var code = query["code"];

        if (string.IsNullOrEmpty(userId) || string.IsNullOrEmpty(code))
        {
            _logger.LogError("Failed to parse userId or code from the backend confirmation link.");
            throw new InvalidOperationException("Invalid confirmation link generated by the Identity framework.");
        }

        var encodedCode = HttpUtility.UrlEncode(code);
        var spaLink = $"{_options.FrontendBaseUrl.TrimEnd('/')}/confirm-email?userId={userId}&code={encodedCode}";

        var htmlContent = GenerateRpgEmailTemplate(
            title: "Forge Your Legacy",
            header: "Verify Your Identity",
            body: "Hail, Champion! Before you step into the arena, you must bind this email to your soul. Click the button below to verify your identity.",
            buttonText: "Verify Email",
            buttonLink: spaLink);

        await SendEmailAsync(email, "Guild Arena - Verify Your Identity", htmlContent);
    }

    /// <summary>
    /// Extracts the reset code from the backend-generated reset link,
    /// rewrites the URL to point to the Blazor SPA, and dispatches the email.
    /// </summary>
    public async Task SendPasswordResetLinkAsync(ApplicationUser user, string email, string resetLink)
    {
        ArgumentNullException.ThrowIfNull(user);
        ArgumentException.ThrowIfNullOrWhiteSpace(email);
        ArgumentException.ThrowIfNullOrWhiteSpace(resetLink);

        var uri = new Uri(resetLink);
        var query = HttpUtility.ParseQueryString(uri.Query);
        var code = query["code"];

        if (string.IsNullOrEmpty(code))
        {
            _logger.LogError("Failed to parse code from the backend reset link.");
            throw new InvalidOperationException("Invalid reset link generated by the Identity framework.");
        }

        var encodedCode = HttpUtility.UrlEncode(code);
        var encodedEmail = HttpUtility.UrlEncode(email);
        var spaLink = $"{_options.FrontendBaseUrl.TrimEnd('/')}/reset-password?email={encodedEmail}&code={encodedCode}";

        var htmlContent = GenerateRpgEmailTemplate(
            title: "A Forgotten Password",
            header: "Restore Your Access",
            body: "A request has been made to reforge your access key. If this was you, proceed through the portal below. If not, guard your credentials fiercely.",
            buttonText: "Reset Password",
            buttonLink: spaLink);

        await SendEmailAsync(email, "Guild Arena - Restore Your Access", htmlContent);
    }

    /// <summary>
    /// Sends a direct password reset code (typically used for API endpoints or 2FA flows).
    /// </summary>
    public async Task SendPasswordResetCodeAsync(ApplicationUser user, string email, string resetCode)
    {
        ArgumentNullException.ThrowIfNull(user);
        ArgumentException.ThrowIfNullOrWhiteSpace(email);
        ArgumentException.ThrowIfNullOrWhiteSpace(resetCode);

        var htmlContent = GenerateRpgEmailTemplate(
            title: "A Forgotten Password",
            header: "Your Secret Rune",
            body: $"A request has been made to reforge your access key. Provide the following ancient rune to the guardian:<br><br><span style='font-size: 28px; font-weight: bold; color: #d4af37; letter-spacing: 6px;'>{resetCode}</span>",
            buttonText: "Return to Arena",
            buttonLink: _options.FrontendBaseUrl);

        await SendEmailAsync(email, "Guild Arena - Password Reset Code", htmlContent);
    }

    /// <summary>
    /// Handles the HTTP POST request to the Brevo v3 API payload.
    /// </summary>
    private async Task SendEmailAsync(string toEmail, string subject, string htmlContent)
    {
        var payload = new
        {
            sender = new { name = _options.SenderName, email = _options.SenderEmail },
            to = new[] { new { email = toEmail } },
            subject = subject,
            htmlContent = htmlContent
        };

        var json = JsonSerializer.Serialize(payload);
        using var content = new StringContent(json, Encoding.UTF8, "application/json");

        var client = _httpClientFactory.CreateClient("BrevoClient");
        var response = await client.PostAsync("smtp/email", content);

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();
            _logger.LogError("Brevo API error: {StatusCode} - {ErrorBody}", response.StatusCode, errorBody);
            throw new HttpRequestException($"Failed to send email via Brevo. Status: {response.StatusCode}");
        }

        _logger.LogInformation("Successfully dispatched email to {Email} via Brevo.", toEmail);
    }

    /// <summary>
    /// Generates a standardized, responsive HTML email template with a Dark Fantasy / RPG aesthetic.
    /// </summary>
    private static string GenerateRpgEmailTemplate(string title, string header, string body, string buttonText, string buttonLink)
    {
        return $@"
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset='utf-8'>
            <style>
                @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&family=Lora:ital,wght@0,400;0,700;1,400&display=swap');
                body {{
                    background-color: #0a0a0c;
                    color: #d1d1d1;
                    font-family: 'Lora', serif;
                    margin: 0;
                    padding: 0;
                }}
                .container {{
                    max-width: 600px;
                    margin: 40px auto;
                    background-color: #141416;
                    border: 1px solid #d4af37;
                    border-radius: 4px;
                    box-shadow: 0 0 20px rgba(212, 175, 55, 0.15);
                    overflow: hidden;
                }}
                .header {{
                    background-color: #050505;
                    padding: 30px;
                    text-align: center;
                    border-bottom: 1px solid #2a2a2a;
                }}
                .header h1 {{
                    font-family: 'Cinzel', serif;
                    color: #d4af37;
                    margin: 0;
                    font-size: 26px;
                    text-transform: uppercase;
                    letter-spacing: 3px;
                }}
                .content {{
                    padding: 40px 30px;
                    text-align: center;
                    line-height: 1.7;
                    font-size: 16px;
                }}
                .content h2 {{
                    font-family: 'Cinzel', serif;
                    color: #ffffff;
                    margin-top: 0;
                    font-size: 22px;
                }}
                .btn-container {{
                    margin-top: 40px;
                    margin-bottom: 20px;
                }}
                .btn {{
                    display: inline-block;
                    background-color: #610000;
                    color: #ffffff;
                    text-decoration: none;
                    padding: 14px 35px;
                    font-family: 'Cinzel', serif;
                    font-weight: bold;
                    border: 1px solid #d4af37;
                    border-radius: 3px;
                    text-transform: uppercase;
                    letter-spacing: 2px;
                    transition: background-color 0.3s;
                }}
                .footer {{
                    background-color: #050505;
                    padding: 20px;
                    text-align: center;
                    font-size: 13px;
                    color: #777;
                    border-top: 1px solid #2a2a2a;
                }}
            </style>
        </head>
        <body>
            <div class='container'>
                <div class='header'>
                    <h1>{title}</h1>
                </div>
                <div class='content'>
                    <h2>{header}</h2>
                    <p>{body}</p>
                    <div class='btn-container'>
                        <a href='{buttonLink}' class='btn'>{buttonText}</a>
                    </div>
                </div>
                <div class='footer'>
                    &copy; {DateTime.UtcNow.Year} Guild Arena. All rights reserved.<br>
                    Forged in the fires of .NET 9.
                </div>
            </div>
        </body>
        </html>";
    }
}