using System.Web;
using GuildArena.Application.Abstractions;
using GuildArena.Domain.Entities;
using GuildArena.Infrastructure.Options;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace GuildArena.Infrastructure.Services.Email;

/// <summary>
/// Intercepts framework-generated identity emails to rewrite API-bound URLs 
/// into SPA-bound URLs and formats the messages using standard HTML templates.
/// </summary>
public class SpaIdentityEmailSender : IEmailSender<ApplicationUser>
{
    private readonly IEmailDispatcher _emailDispatcher;
    private readonly EmailOptions _options;
    private readonly ILogger<SpaIdentityEmailSender> _logger;
    private string? _templateCache;

    public SpaIdentityEmailSender(
        IEmailDispatcher emailDispatcher,
        IOptions<EmailOptions> options,
        ILogger<SpaIdentityEmailSender> logger)
    {
        _emailDispatcher = emailDispatcher;
        _options = options.Value;
        _logger = logger;
    }

    /// <inheritdoc />
    public async Task SendConfirmationLinkAsync(ApplicationUser user, string email, string confirmationLink)
    {
        var uri = new Uri(confirmationLink);
        var query = HttpUtility.ParseQueryString(uri.Query);
        var userId = query["userId"];
        var code = query["code"];

        if (string.IsNullOrEmpty(userId) || string.IsNullOrEmpty(code))
        {
            _logger.LogError("Failed to parse confirmation link: {Link}", confirmationLink);
            throw new InvalidOperationException("Invalid confirmation link generated by the Identity framework.");
        }

        var encodedCode = HttpUtility.UrlEncode(code);
        var spaLink = $"{_options.FrontendBaseUrl.TrimEnd('/')}/confirm-email?userId={userId}&code={encodedCode}";

        var html = await GenerateEmailHtmlAsync(
            title: "GuildArena",
            header: "Verify Your Email Address",
            body: "Thank you for registering. Please click the button below to verify your email address and complete your account setup.",
            buttonText: "Verify Email",
            buttonLink: spaLink);

        await _emailDispatcher.DispatchAsync(email, "GuildArena - Account Verification", html);
    }

    /// <inheritdoc />
    public async Task SendPasswordResetLinkAsync(ApplicationUser user, string email, string resetLink)
    {
        var uri = new Uri(resetLink);
        var query = HttpUtility.ParseQueryString(uri.Query);
        var code = query["code"];

        if (string.IsNullOrEmpty(code))
        {
            _logger.LogError("Failed to parse reset link: {Link}", resetLink);
            throw new InvalidOperationException("Invalid reset link generated by the Identity framework.");
        }

        var encodedCode = HttpUtility.UrlEncode(code);
        var encodedEmail = HttpUtility.UrlEncode(email);
        var spaLink = $"{_options.FrontendBaseUrl.TrimEnd('/')}/reset-password?email={encodedEmail}&code={encodedCode}";

        var html = await GenerateEmailHtmlAsync(
            title: "GuildArena",
            header: "Password Reset Request",
            body: "We received a request to reset the password associated with your account. If you made this request, please click the button below. Otherwise, you can safely ignore this email.",
            buttonText: "Reset Password",
            buttonLink: spaLink);

        await _emailDispatcher.DispatchAsync(email, "GuildArena - Password Reset Request", html);
    }

    /// <inheritdoc />
    public async Task SendPasswordResetCodeAsync(ApplicationUser user, string email, string resetCode)
    {
        var html = await GenerateEmailHtmlAsync(
            title: "GuildArena",
            header: "Password Reset Code",
            body: $"We received a request to reset your password. Please use the following authorization code to proceed:<br><br><span style='font-size: 24px; font-weight: bold; color: #d4af37; letter-spacing: 4px;'>{resetCode}</span><br><br>If you did not request this, please safely ignore this email.",
            buttonText: "Return to Website",
            buttonLink: _options.FrontendBaseUrl);

        await _emailDispatcher.DispatchAsync(email, "GuildArena - Password Reset Code", html);
    }

    private async Task<string> GenerateEmailHtmlAsync(string title, string header, string body, string buttonText, string buttonLink)
    {
        if (_templateCache == null)
        {
            var templatePath = Path.Combine(AppContext.BaseDirectory, "Services", "Email", "Template", "StandardTemplate.html");
            _templateCache = await File.ReadAllTextAsync(templatePath);
        }

        return _templateCache
            .Replace("{{TITLE}}", title)
            .Replace("{{HEADER}}", header)
            .Replace("{{BODY}}", body)
            .Replace("{{BUTTON_TEXT}}", buttonText)
            .Replace("{{BUTTON_LINK}}", buttonLink)
            .Replace("{{YEAR}}", DateTime.UtcNow.Year.ToString());
    }
}