namespace GuildArena.Domain.Enums;

public enum ModifierTrigger
{
    PASSIVE,
    ON_TURN_START,
    ON_TURN_END,
    ON_DEAL_MELEE_ATTACK,
    ON_RECEIVE_MELEE_ATTACK,
    ON_DEAL_RANGED_ATTACK,
    ON_RECEIVE_RANGED_ATTACK,
    ON_DEAL_MAGIC_DAMAGE,
    ON_RECEIVE_DAMAGE,
    ON_DEAL_DAMAGE,
    ON_DEATH
}
